<?php

/**
 * @file
 * Provides a Markdown Extra input filter.
 */

/**
 * Implements hook_filter_info().
 */
function markdownextra_filter_info() {
  $filters['filter_markdownextra'] = array(
    'title' => t('Markdown Extra'),
    'description' => t('Allows content to be submitted using Markdown Extra, a simple plain-text syntax that is filtered into valid XHTML.'),
    'process callback' => '_filter_markdownextra',
    'tips callback' => '_filter_markdownextra_tips',
  );

  return $filters;
}

/**
 * Returns the markdownextra input filter tips.
 */
function _filter_markdownextra_tips($format, $long = FALSE) {
  if ($long) {
    return t('Quick Tips:<ul>
      <li>Two or more spaces at a line\'s end = Line break</li>
      <li>Double returns = Paragraph</li>
      <li>*Single asterisks* or _single underscores_ = <em>Emphasis</em></li>
      <li>**Double** or __double__ = <strong>Strong</strong></li>
      <li>This is [a link](http://the.link.example.com "The optional title text")</li>
      </ul>For complete details on the Markdown syntax, see the <a href="http://daringfireball.net/projects/markdown/syntax">Markdown documentation</a> and <a href="http://michelf.com/projects/php-markdown/extra/">Markdown Extra documentation</a> for tables, footnotes, and more.');
  }
  else {
    return t('You can use <a href="@filter_tips">Markdown syntax</a> to format and style the text. Also see <a href="@markdown_extra">Markdown Extra</a> for tables, footnotes, and more.', array('@filter_tips' => url('filter/tips'), '@markdown_extra' => 'http://michelf.com/projects/php-markdown/extra/'));
  }
}

/**
 * Implements hook_block_view().
 */
function markdownextra_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'markdownextra_help':
      $block['title'] = t('Markdown filter tips');
      $block['content'] = _markdownextra_help_block();
      break;
  }

  return $block;
}

/**
 * Implements hook_block_info().
 */
function markdownextra_block_info() {
  $blocks = array();
  $blocks['markdownextra_help'] = array(
    'info' => t('Markdown Extra filter tips'),
  );

  return $blocks;
}

/**
 * Provides content for the markdownextra help block.
 */
function _markdownextra_help_block() {
  return '<pre>' . t("
## Header 2 ##
### Header 3 ###
#### Header 4 ####
##### Header 5 #####
(Hashes on right are optional)

Link [Backdrop CMS](https://backdropcms.org/)

Inline markup like _italics_,
 **bold**, and `code()`.

> Blockquote. Like email replies
>> And, they can be nested

* Bullet lists are easy too
- Another one
+ Another one

1. A numbered list
2. Which is numbered
3. With periods and a space

And now some code:
    // Code is indented text
    is_easy() to_remember();") . '</pre>';
}

/**
 * Filter process callback.
 */
function _filter_markdownextra($text, $format) {
  if (!empty($text)) {
    module_load_include('php', 'markdownextra', 'MarkdownExtra.inc');
    $text = \Michelf\MarkdownExtra::defaultTransform($text);
  }

  return $text;
}
